### ISSUE TITLE
breaking refactors for webp-hero

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/webp-hero#19]
here are some refactors i'm interested to make before webp-hero `v0.0.0`:

- [ ] webp-machine becomes decoupled from `detectWebpSupport`
  - users are expected to use `detectWebpSupport` themselves, and then use a webp-machine or not
  - explained more in #13  
    &nbsp;
- [ ] webp-machine becomes decoupled from polyfilling logic
  - the machine decodes webp images, and keeps a cache so work is not repeated
  - it has no polyfilling logic
  - cache should probably operate on a data checksum rather than src  
    &nbsp;
- [ ] webp-polyfill.ts becomes the new home for polyfilling logic
  - it might be a class that extends the webp-machine
  - otherwise it might just be a function that returns more functions  
    &nbsp;
- [ ] high level helper functions are added as needed for convenience
  - `useWebpPolyfill()` might detectWebpSupport and then use webp-polyfilling logic when needed
    - it would probably return an object that contains a `polyfillWebp()` function, which can be called whenever you change routes or images on the page  
    &nbsp;
- [ ] consider renaming webp-machine to "webp-decoder"
  - this is anticipating the future possibility of a "webp-encoder", in which case "webp-machine" should contain both the decoder and encoder
  - it would be best if people started specifically using `webp-decoder` now, instead of using `webp-machine` which in the future won't be optimum for the polyfilling (decoding-only) use-case
  - **[edit]:** similarly, probably should rename `webp.js` to `dwebp.js` in `libwebp/dist/`, see #20 

@Drummi42 — i noticed you have begun some polyfilling work in https://github.com/Drummi42/webp-hero/commit/377b4e3b08fa12433ae6690aaf936ffcb24a591a, so i'm pinging you now to show you my plans to refactor webp-hero — i'd like to learn more about your use-case, let's work together :)

**Comment by Drummi42** [comment]
Yo! I am very busy lately with tasks at work as the time will certainly to write

**Comment by chase-moskal** [comment]
closing due to lack of priority
