### ISSUE TITLE
Support encoder

### ISSUE THREAD

**Issue by tomasdev** [chase-moskal/webp-hero#2]
## Support for `canvas.toDataURL('image/webp')`

Given that libwebp is included, why not use it for encoding as well as decoding polyfill?

**Comment by chase-moskal** [comment]
we can add the encoder too, if you'd like

currently, webp-hero's browser polyfill only provides decoding for the purpose of allowing webp images to be viewed in browsers that don't support webp, like firefox, safari, and edge

the docker image within webp-hero creates an emscripten build of libwebp, and then a node script wraps the decoder in a javascript module -- this setup could be extended to also prepare an encoder javascript module

**Comment by chase-moskal** [comment]
i was just imagining what the use-case might be...

webp-hero could actually become a 100% clientside app for easy drag-and-drop image conversion to and from wepb format -- that would sure be handy!

**Comment by tomasdev** [comment]
Hi Chase

It would also be useful to convert png to webp in iOS in order to create a
polyfill of MediaRecorder API using webm as output video.

**Comment by tomasdev** [comment]
I lack the knowledge to include the encoding function from the Docker emscripten. webptosdl has a C file definition, the encoder is just part of the lib, and my C skills are nonexistent.

**Comment by chase-moskal** [comment]
you'd be surprised how out-of-my-depth i felt putting webp-hero together, the complexity of the libwebp emscripten build can make your head spin

[this docker file "libwebpjs/Dockerfile"](https://github.com/chase-moskal/webp-hero/blob/master/libwebpjs/Dockerfile) downloads and runs the libwebp emscripten build, and generates the output "dist/dwebp.js"

[this cmake config file "libwebpjs/source/CMakeLists.txt"](https://github.com/chase-moskal/webp-hero/blob/master/libwebpjs/source/CMakeLists.txt) has been customized by me (to increase virtual memory allowance, etc), and is provided to the libwebp build

[this webp-hero javascript file "source/webp-hero.ts"](https://github.com/chase-moskal/webp-hero/blob/95383413011ef783fea93763635c8d4d01e1c2dd/source/webp-hero.ts#L46) provides a nice user-facing ergonomics for interacting with dwebp

**for the task of including encoder functionality into webp-hero**, i believe we would probably need to touch all three files

it's not yet clear to me whether we'd rather produce a `cwebp.js` alongside `dwebp.js`, and then provide a number of different bundles for different use-cases (`webp-hero-decode.js`, `webp-hero-encode.js`, and `webp-hero-decode-and-encode.js`) — or if we just lump it all into one fat bundle

heck, it's not even clear to me whether or not all the encoder functionality is already present in `dwebp.js` as it stands, and that maybe we'd merely have to add the encoding function to that final ergonomic webp-hero javascript interface

**Comment by jvenema** [comment]
Was this closed/completed or closed/won't do?

**Comment by tomasdev** [comment]
Closed wont do.

Technically is possible but the performance is awful. I have done it at around 200ms per frame. That is unusable for any real life application.

It would mean the user has to wait literally minutes for just seconds of recording to be processed, giving a less than ideal experience.

**Comment by chase-moskal** [comment]
hey, i decided to reopen this since there seems to be interest for the feature

> Technically is possible but the performance is awful. I have done it at around 200ms per frame.

at the moment webp-hero's use-case is only concerned with the conversion of still images, for which case i think 200ms to convert a jpg would be a nice experience if we wanted to create a web app to convert images on the clientside

i don't now have the time, but i would be interested to accept contributions that would make webp-hero more robust, and have an entrypoint that allows for encoding too, which could open the door to making a nice handy webp converter web-app that works entirely clientside and offline

in issue #19 i lay out some ideas for potential breaking refactors that could improve the architecture if we were to include encoder functionality

**Comment by chase-moskal** [comment]
closed due to lack of priority

if you're interested in this feature, please consider opening a new issue and we can chat about it!
