### ISSUE TITLE
polyfills locked inputs?

### ISSUE THREAD

**Issue by Drummi42** [chase-moskal/webp-hero#21]
When the run was polyfills, it is impossible to enter something in the inputs and refresh the page ctrl+f5. That only my wrong?
UPD: sorry, haven't read other issues :C

**Comment by Drummi42** [comment]
Event Listener "keypress" on document

**Comment by Drummi42** [comment]
Problem methods "receiveEvent", "lookupKeyCodeForEvent", "handleEvent", "flushEventsToHandler", "pollEvent" in webpjs. That SDL library methods.  They locked all keyboard events.

**Comment by jscher2000** [comment]
I see this problem in Firefox and Chrome on 

https://chasemoskal.com/webp-hero/?force

For example, can't Page Up/Down, Ctrl+u is ignored. Is there a solution here or upstream?

**Comment by chase-moskal** [comment]
@jscher2000 — thanks for letting me know. i hadn't noticed this issue before, but i can confirm it seems to reproduce on chrome

i think this is a duplicate of #18, which identifies that emscripten/sdk seems to be intercepting and blocking the keyboard input. let's continue this issue from there
