### ISSUE TITLE
Does not work with URL with parameters.

### ISSUE THREAD

**Issue by mikunimaru** [chase-moskal/webp-hero#22]
It does not detect URL with parameter, for example 
"https://chasemoskal.com/webp-hero/images/dice.webp?foo".

**Comment by chase-moskal** [comment]
thank you for reporting this issue :)

next we need to

- [x] identify the cause of this bug
  the regex in webp-machine on image src was too restrictive
- [x] launch a pull request which implements a fix
- [x] merge the pr

contributions welcome

**Comment by chase-moskal** [comment]
@Lobasya — thanks for contributing on this issue

there was an error with your pull request, so i closed #24 

we really want to receive your contributions, so hopefully you can post a new pull request, or perhaps explain any findings about the root cause of the bug in this issue

thanks :wave:

**Comment by chase-moskal** [comment]
this bug has been fixed in `webp-hero@0.0.0-dev.23`
