### ISSUE TITLE
picture / srcset support

### ISSUE THREAD

**Issue by glomotion** [chase-moskal/webp-hero#26]
demo:
https://codepen.io/glomotion/pen/GVqmwe

Looks like the current shim doesn't work when using webp's inside srcset="" definitions...
I think I can guess why ... srcset's make things a whole lot more complicated... 

Are there any plans to try to support this?

**Comment by chase-moskal** [comment]
hello @glomotion, thanks for filing this issue

this is a great idea, and would be a worthwhile enhancement!

currently, webp-hero doesn't work with CSS images (like `background-image`) or with `<picture>` elements -- webp-hero only works with regular `<img>` elements

i've added this ticket as an enhancement to the [webp-hero roadmap](https://github.com/chase-moskal/webp-hero/projects/2)

i have some refactor plans for webp-hero, but i'm not sure when i might be able to get around to it

pull request contributions are welcome, some work would have to be done on the [polyfillDocument method in webp-machine.ts](https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L86)

:wave: Chase

**Comment by chase-moskal** [comment]
closing due to lack of priority

this deficiency is now mentioned in the readme

i'm still keen on the issue, so if anybody is interested in working on this, please open a new issue and we'll chat about it!
