### ISSUE TITLE
Release memory

### ISSUE THREAD

**Issue by Ben-Mack** [chase-moskal/webp-hero#28]
Currently [homepage](https://chasemoskal.com/webp-hero/?force) always takes near 100MB of memory
![Annotation 2019-09-05 123451](https://user-images.githubusercontent.com/6309393/64314565-99ff2980-cfd9-11e9-8d1b-b0df53578e5e.png)

For larger image (4096px), the memory taken even going up to 500MB.

How to release these ArrayBuffer after decoded all images?

**Comment by chase-moskal** [comment]
@Ben-Mack — memory management is a very important topic for webp-hero

i haven't really looked into it, and i myself do not personally understand how to control memory management regarding the libwebp emscripten build — at some point, i naively increased a total memory allowance emscripten setting, when webp-hero was running out of memory at runtime (see a diff from `CMakeLists.original.txt` to `CmakeLists.txt` in [webp-hero/libwebp/source](https://github.com/chase-moskal/webp-hero/tree/master/libwebp/source) for more info)

i believe we would need to do some research into memory management in emscripten, and how google's [libwebp](https://github.com/webmproject/libwebp) can be configured

i think an enhancement related to this issue would be implemented as changes to the [webp-hero/libwebp dockerfile](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/Dockerfile) and associated configurations

alternatively, it's possible that the emscripten build could have functionality at runtime to release memory, in which case, that functionality would probably need to be exposed via the wrapper (see [wrapping-end.js.txt](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/wrapping-end.js.txt) and [wrapping-end.cjs.js.txt](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/wrapping-end.cjs.js.txt))

if anybody has any ideas about this topic, we'd love to hear about it!

cheers,

:wave: Chase

**Comment by Nantris** [comment]
@Ben-Mack what environment are you measuring usage in (and what tool?) Chrome has, pretty much forever and I think still even now, had a memory leak with Base64 images. Have you tested overall memory usage using png or jpg Base64 images?

Memory should be freed automatically by the JavaScript engine shortly after the value is no longer accessible in any running code.

@chase-moskal are the array buffers assigned to the `window` object or something else where they'll remain accessible indefinitely?

**Comment by Nantris** [comment]
@chase-moskal what if we set `this.cache[src]` to null after polyfilling here? https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L68 and here https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L73 

The only downside I see is if multiple copies of the same image are rendered multiple times on the page, we'll be clearing the cached value. We can probably work around this by created checking whether a `src` is used again on the page before dropping it from the cache.

**Comment by chase-moskal** [comment]
@Slapbox — excellent observation, i think the cache is consuming a lot of memory, being that it's saving all of the decoded PNG data and hanging onto it

we should be mindful of a usecase where: a developer who adds new content to the page (via ajax, or component rendering) will want to be able to simply re-run webp-hero `polyfillDocument` method anytime content may have changed — so we want the cached images to remain available

i propose we could add a `clearCache()` method which simply releases the cache, and the developer is responsible to decide when it's a good idea to do this — also it could be desirable to replace the current cache implementation with a `Map` object, or maybe we could figure something smart involving `WeakMap` to better manage this memory (perhaps we could hold references to existing `img` elements to avoid data duplication between image elements and the cache (however we'd need to ensure CSS images and picture elements and the rest could still work in such a system))

also, it may or may not be worth looking deeper into the way emscripten programs work, i believe it will allocate a bunch of memory space in array buffers, which the asm code will operate on during runtime, and there might be some special considerations to be taken to clear the memory space consumed by the emscripten program after work is completed (perhaps there could be a `shutdown()` method to dispose of the emscripten memory when work is completed)

**Comment by Ben-Mack** [comment]
@Slapbox It's just the memory tool in Firefox browser.

@chase-moskal Adding `shutdown` method to dispose all memory in cache and emscripten seems like a perfect fit for my use case

**Comment by chase-moskal** [comment]
@Ben-Mack — here's some reading material i thought might be relevant on the subject

- [emscripten docs about avoiding memory spikes](https://emscripten.org/docs/optimizing/Optimizing-Code.html#avoid-memory-spikes-by-separating-out-asm-js)
- [here the creator of empscripten mentions a function](https://github.com/emscripten-core/emscripten/issues/6484#issuecomment-385490578) called `Module._free(ptr)`
- if we were to expose a function using `Module._free(ptr)`, i believe it would be exposed in [wrapping-end.js.txt](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/wrapping-end.js.txt) and also its [common-js counterpart](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/wrapping-end.cjs.js.txt)

:wave:

**Comment by ghost** [comment]
I also have issues with memory. I am using this library with React like this:
```typescript
  useEffect(() => {
    var webpMachine: any = new WebpMachine()
    webpMachine.polyfillDocument()

    return () => {
      webpMachine = undefined
    }
  }, [html])
```
On Safari iOS as well as macOS both the most recent versions the Site periodically crashes this is indicated by Safari saying "There has been a repeated problem on the website..". Now I am aware that what Im doing in my code is not the most efficient way however it still indicates some issue likely a memory issue in this library.

**Comment by Nantris** [comment]
@OneAndOnlyOdin - Noooooooooooo!

Only run `new WebpMachine()` once, and in a higher scope! You can run `webpMachine.polyfillDocument()` as often as you like though.

**Comment by ghost** [comment]
Yes, this does the trick. Thank you for the Tip.

**Comment by chase-moskal** [comment]
@Ben-Mack @Slapbox — `clearCache` has been added and published in the latest version of webp-hero
