### ISSUE TITLE
upgrade libwebp/emscripten, refactor the build, enable wasm/workers

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/webp-hero#31]
hello, today i wanted to fix #18 and also routinely upgrade libwebp and emscripten
however, there have been some changes to emsdk, and now the existing build is failing,

the work is in the [fail](https://github.com/chase-moskal/webp-hero/tree/fail) branch

here's the error... when we're trying to use the same versions of emscripten and libwebp (emsdk actually doesn't have the exact version we want, so we had to jump forward from 1.38.30 to 1.38.48)

```
[ 80%] Linking C executable webp.js
shared:ERROR: Memory growth is not supported with pthreads without wasm
make[2]: *** [webp.js] Error 1
CMakeFiles/webp_js.dir/build.make:98: recipe for target 'webp.js' failed
CMakeFiles/Makefile2:291: recipe for target 'CMakeFiles/webp_js.dir/all' failed
make[1]: *** [CMakeFiles/webp_js.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/bash -c cd /work/emsdk   && source ./emsdk_env.sh   && cd /work/libwebp/webp_js   && cmake -DWEBP_BUILD_WEBP_JS=ON     -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1     -DCMAKE_TOOLCHAIN_FILE=/work/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake     ../   && make' returned a non-zero code: 2
```

when this didn't work, i also tried upgrading emscripten and libwebpjs all to the latest versions, however this fails with a different error:

```
[ 71%] Linking C static library libwebp.bc
shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning                                                                                                                              
wasm-ld: error: 'atomics' feature is used by CMakeFiles/webpdecode.dir/src/dec/alpha_dec.c.o, so --shared-memory must be used          
shared:ERROR: '/work/emsdk/upstream/bin/wasm-ld -o libwebp.bc --allow-undefined --lto-O0 CMakeFiles/webpdecode.dir/src/dec/alpha_dec.c.o CMakeFiles/webpdecode.dir/src/dec/buffer_dec.c.o -L/work/emsdk/upstream/emscripten/system/local/lib CMakeFiles/webpdecode.dir/src/dec/frame_dec.c.o -L/work/emsdk/upstream/emscripten/system/lib CMakeFiles/webpdecode.dir/src/dec/idec_dec.c.o -L/root/.emscripten_cache/wasm-obj CMakeFiles/webpdecode.dir/src/dec/io_dec.c.o CMakeFiles/webpdecode.dir/src/dec/quant_dec.c.o CMakeFiles/webpdecode.dir/src/dec/tree_dec.c.o CMakeFiles/webpdecode.dir/src/dec/vp8_dec.c.o CMakeFiles/webpdecode.dir/src/dec/vp8l_dec.c.o CMakeFiles/webpdecode.dir/src/dec/webp_dec.c.o CMakeFiles/webpdsp.dir/src/dsp/alpha_processing.c.o CMakeFiles/webpdsp.dir/src/dsp/cpu.c.o CMakeFiles/webpdsp.dir/src/dsp/dec.c.o CMakeFiles/webpdsp.dir/src/dsp/dec_clip_tables.c.o CMakeFiles/webpdsp.dir/src/dsp/filters.c.o CMakeFiles/webpdsp.dir/src/dsp/lossless.c.o CMakeFiles/webpdsp.dir/src/dsp/rescaler.c.o CMakeFiles/webpdsp.dir/src/dsp/upsampling.c.o CMakeFiles/webpdsp.dir/src/dsp/yuv.c.o CMakeFiles/webpdsp.dir/src/dsp/cost.c.o CMakeFiles/webpdsp.dir/src/dsp/enc.c.o CMakeFiles/webpdsp.dir/src/dsp/lossless_enc.c.o CMakeFiles/webpdsp.dir/src/dsp/ssim.c.o CMakeFiles/webpencode.dir/src/enc/alpha_enc.c.o CMakeFiles/webpencode.dir/src/enc/analysis_enc.c.o CMakeFiles/webpencode.dir/src/enc/backward_references_cost_enc.c.o CMakeFiles/webpencode.dir/src/enc/backward_references_enc.c.o CMakeFiles/webpencode.dir/src/enc/config_enc.c.o CMakeFiles/webpencode.dir/src/enc/cost_enc.c.o CMakeFiles/webpencode.dir/src/enc/filter_enc.c.o CMakeFiles/webpencode.dir/src/enc/frame_enc.c.o CMakeFiles/webpencode.dir/src/enc/histogram_enc.c.o CMakeFiles/webpencode.dir/src/enc/iterator_enc.c.o CMakeFiles/webpencode.dir/src/enc/near_lossless_enc.c.o CMakeFiles/webpencode.dir/src/enc/picture_enc.c.o CMakeFiles/webpencode.dir/src/enc/picture_csp_enc.c.o CMakeFiles/webpencode.dir/src/enc/picture_psnr_enc.c.o CMakeFiles/webpencode.dir/src/enc/picture_rescale_enc.c.o CMakeFiles/webpencode.dir/src/enc/picture_tools_enc.c.o CMakeFiles/webpencode.dir/src/enc/predictor_enc.c.o CMakeFiles/webpencode.dir/src/enc/quant_enc.c.o CMakeFiles/webpencode.dir/src/enc/syntax_enc.c.o CMakeFiles/webpencode.dir/src/enc/token_enc.c.o CMakeFiles/webpencode.dir/src/enc/tree_enc.c.o CMakeFiles/webpencode.dir/src/enc/vp8l_enc.c.o CMakeFiles/webpencode.dir/src/enc/webp_enc.c.o CMakeFiles/webputils.dir/src/utils/bit_reader_utils.c.o CMakeFiles/webputils.dir/src/utils/color_cache_utils.c.o CMakeFiles/webputils.dir/src/utils/filters_utils.c.o CMakeFiles/webputils.dir/src/utils/huffman_utils.c.o CMakeFiles/webputils.dir/src/utils/quant_levels_dec_utils.c.o CMakeFiles/webputils.dir/src/utils/rescaler_utils.c.o CMakeFiles/webputils.dir/src/utils/random_utils.c.o CMakeFiles/webputils.dir/src/utils/thread_utils.c.o CMakeFiles/webputils.dir/src/utils/utils.c.o CMakeFiles/webputils.dir/src/utils/bit_writer_utils.c.o CMakeFiles/webputils.dir/src/utils/huffman_encode_utils.c.o CMakeFiles/webputils.dir/src/utils/quant_levels_utils.c.o --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024 --relocatable' failed (1)
make[2]: *** [CMakeFiles/webp.dir/build.make:187: libwebp.bc] Error 1
make[1]: *** [CMakeFiles/Makefile2:298: CMakeFiles/webp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
The command '/bin/bash -c cd /work/emsdk   && source ./emsdk_env.sh   && cd /work/libwebp/webp_js   && cmake -DWEBP_BUILD_WEBP_JS=ON     -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1     -DCMAKE_TOOLCHAIN_FILE=/work/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake     ../   && make' returned a non-zero code: 2
```

so currently there's no new libwebp builds we can use, so webp-hero is stuck until this is figured out :man_shrugging: 

i'm out of time for now, hopefully next time i try this, the stars will align and a new version combo of emscripten and libwebp will work

the solution is probably to try many combinations of versions between emscripten and libwebp, and to pull your hair out for about two days trudging through weird errors

**Comment by chase-moskal** [comment]
i had posted a bug report to libwebp: https://bugs.chromium.org/p/webp/issues/detail?id=454

they responded with some advice, and soon i ought to look into it further and see if we can resolve this issue, or at least post back whatever results i might find

**Comment by chase-moskal** [comment]
okay, we've fixed the build, but we had to unwind some hacks that disabled wasm, the hacks aren't working anymore

plus, wasm would actually be a big win

so i'm determined to get webp-hero working with the standard libwebpjs wasm build

the latest commit on the `fail` branch, 78193921eb94cae82f27c63f001d7899f421eaee, has a working libwebpjs build, but it's not working at runtime because it's looking for the .wasm files

i've tried to instruct emscripten where to find the wasm files, but it's not working, see https://github.com/emscripten-core/emscripten/issues/10434

after we fix the above emscripten issue, we'll have a new shiny upgraded webp-hero that should use wasm and even web workers and maybe threading and stuff

**Comment by chase-moskal** [comment]
man, this situation is a mess

i can't get google's libwebp building correctly

we want an asm.js build for ie11, and a modern wasm build for safari

i created an [issue on webp's bug tracker](https://bugs.chromium.org/p/webp/issues/detail?id=470) asking for advice about how to get the asm.js build working

**Comment by chase-moskal** [comment]
OKAY, i finally rebuilt libwebp, which unblocks further development on webp-hero. i merged neo's base64 support, and have updated the readme in the latest published version

i abandoned the effort to explore wasm or web workers -- i'm just glad it's working again

**Comment by cyan-2048** [comment]
did you get that asm.js support working?

**Comment by chase-moskal** [comment]
hey. if i'm remembering correctly, i think webp-hero is using an asm.js build, and i was having trouble getting it to work with a wasm build. but, since all the evergreen browsers support webp, webp-hero is more of a legacy thing anyways, so wasm support would probably be counter productive, i think.

**Comment by cyan-2048** [comment]
> hey. if i'm remembering correctly, i think webp-hero is using an asm.js build, and i was having trouble getting it to work with a wasm build. but, since all the evergreen browsers support webp, webp-hero is more of a legacy thing anyways, so wasm support would probably be counter productive, i think.

well from what i'm seeing it isn't using asm.js (you can't find `"use asm";` anywhere in the code), just incase you would want asm.js to actually work here's a bit of info:

1. use an old version of emscripten with fast-comp ([see this issue for more info](https://github.com/emscripten-core/emscripten/issues/18013))
2. minifiers will break asm.js (`0.0` is a float type, minifiers will convert that to `0` which in turn breaks asm.js syntax)
3. asm.js does indeed help with performance

what I did for number 2 is I separate the asm.js into a separate js file and assign a global variable to access that code.

**Comment by chase-moskal** [comment]
hello, webp-hero is currently on an asm.js build, the build of libwebp is produced by the dockerfile you'll find [here in the libwebp directory](https://github.com/chase-moskal/webp-hero/tree/master/libwebp) and you'll also find the build artifacts checked in -- i believe this file [webp.js](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/dist/webp.js) is the es module which has the asm baked-in, which webp-hero ultimately uses.

it looks like my approach was similar to yours, except that instead of a global variable, i expose it as an es module export.

**Comment by cyan-2048** [comment]
> hello, webp-hero is currently on an asm.js build, the build of libwebp is produced by the dockerfile you'll find [here in the libwebp directory](https://github.com/chase-moskal/webp-hero/tree/master/libwebp) and you'll also find the build artifacts checked in -- i believe this file [webp.js](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/dist/webp.js) is the es module which has the asm baked-in, which webp-hero ultimately uses.
> 
> it looks like my approach was similar to yours, except that instead of a global variable, i expose it as an es module export.

again that's not asm.js, if it was then you'd find "use asm" in the code, without that specific line of code the browser will not compile it into near native speed.

**Comment by chase-moskal** [comment]
interesting, i wasn't aware that such an optimization is possible -- i was just seeing the term `asm` in [the module](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/dist/webp.js#L4-L6), so i assumed that's all there is to it -- so i suppose it's "unoptimized asm.js" javascript code that isn't being signalled to the browser as something it could optimize.
