### ISSUE TITLE
Need some guide for Nextjs/Reactjs webp intregration

### ISSUE THREAD

**Issue by pyprism** [chase-moskal/webp-hero#34]
Thanks for your awesome project. This is not a direct issue for this library. I am trying to use this library in my Next.js project. But webp image is not rendering in safari browser. Here is what I have tried ; I added this code block in every pages where webp image used. 

```
import React, {useEffect} from "react";
import {WebpMachine} from "webp-hero"

const ExampleComponent = (props) => {
    useEffect(() => {
        const webpMachine = new WebpMachine();
        webpMachine.polyfillDocument();
    });
  return ( //something  )
}
``` 
It would be really helpful if anyone knows what I am missing .

**Comment by chase-moskal** [comment]
hello @pyprism, sorry for my late reply!

you want to create only one instance of the `new WebpMachine()` for the entire page, then find a way to call `polyfillDocument()` again whenever you think new webp images might have appeared on the page

**Comment by EricWVGG** [comment]
I'm giving this a try thusly…

```
// html.js
const html = () => (
  <html>
    <script type="module" dangerouslySetInnerHTML={{
        __html: `
          import {WebpMachine} from "https://unpkg.com/webp-hero@0.0.0-dev.21/dist/webp-machine.js"
          window.webpMachine = new WebpMachine()
          window.webpMachine.polyfillDocument()
        `
      }} />
)

// component
const Image = (props) => {
  const [imageSource, setImageSource] = React.useState("")
  React.useEffect(() => {
    setImageSource(props.src + '?fm=webp') // CDN webp autogenerator
    window.webpMachine.polyfillDocument()
    console.log('ding')
  }, [])
  return (
      <img src={imageSource || ""}
        {...props} 
      />
  )
}
```

Doesn't do anything, sadly.

**Comment by chase-moskal** [comment]
@EricWVGG — i think the issue you're experiencing may be related to #36

**Comment by chase-moskal** [comment]
@EricWVGG — also you should upgrade to `webp-hero@0.0.0-dev.24`

**Comment by chase-moskal** [comment]
closing this stale issue — also consider upgrading to the new version of webp-hero published today

please open another issue if you experience any more problems!
