### ISSUE TITLE
ios 13.4.1 chrome not always displaying webp images

### ISSUE THREAD

**Issue by 360Kreatif** [chase-moskal/webp-hero#35]
I tested my page with my iphone5s safari and chrome...they are working with no problem...but when I test it with iOS 13.4.1 chrome it is not always displaying webp images...sometimes displaying or some of my images displaying...iOS 13.4.1 safari also working correctly...

my url;
https://www.guvenliseyahat.com/elbi/

thanks

**Comment by chase-moskal** [comment]
thanks for this issue report, when i have some time i will see if i can test this out on browserstack

**Comment by chase-moskal** [comment]
hello. i published a fresh version of webp-hero today, however in my testing on browserstack i found that iphone 7 safari seems to work, but older versions seem to not work.. there's a new note about browser support in the readme

now closing this issue, but i am interested in getting webp-hero working on the 5s, so perhaps sometime we can work to debug it and find what's wrong.. however webp-hero also doesn't work in IE10 so its uses are somewhat limited currently

please open a new issue if you have further issues or findings
