### ISSUE TITLE
polyfillImage() only detects webp by regex ".webp" not the content of the actual image

### ISSUE THREAD

**Issue by uznomis** [chase-moskal/webp-hero#37]
I encountered this issue where an img tag with src of a url that doesn't contain ".webp" is not considered a candidate for polyfill. For example, the src url can be "/my-image-route/2" instead of "/my-image-directory/2.webp". Without thorough research, I don't have a solution for this because you would need to decode the downloaded binary to determine if an img tag is really a webp or not. Interested in the community's thoughts.

**Comment by chase-moskal** [comment]
hello @uznomis, thank you for this issue and the pull request

please see issue #27 and #36 

i'm afraid i'm really tied up especially for the next couple of weeks, but i'd really like to see if i can fix the libwebp build and produce a new refactored edition of webp hero which includes many improvements we've talked about in various issues

it should be known also, that the latest version of safari for mac now includes webp support, and i think ios will follow, and so webp-hero's necessity will shrink very small to support legacy browsers

however with webp-hero becoming included in all evergreen browsers, it's possible webp-hero will become a figment of the past

even so, i owe this project a little bit more love, i just can't afford it right now -- last i dived in, i got stuck on this issue building a fresh version of libwebp: https://github.com/chase-moskal/webp-hero/issues/31#issuecomment-630490492

**Comment by uznomis** [comment]
@chase-moskal The “enhancement for web developers” session was the only session I watched in WWDC 2020 and it was an exciting thing to learn that new versions of Safari will support webp out of the box. Majority of the iOS devices will soon get the upgrade, but unfortunately I own an iPad mini 3 which stops at iOS 12. I agree with you the necessity of this package is lessened with that WWDC 2020 announcement. You may close this issue if you want :)

**Comment by chase-moskal** [comment]
closing this issue

the deficiency is now noted in the webp-hero readme

please open a new issue if you'd like to collaborate on eliminating this deficiency, thanks
