### ISSUE TITLE
Minor: URL parameters "?force?useCanvasElements" should be replaced by "?force&useCanvasElements"

### ISSUE THREAD

**Issue by mossroy** [chase-moskal/webp-hero#44]
I think that "?force?useCanvasElements" (used in demo page) is not a valid syntax.

`?` should be used before URL parameters, but they have to be separated by `&` afterwards

**Comment by chase-moskal** [comment]
:wave: fixed in 0a5f289db7b696763da7c691101e6ebcd1146753
