### ISSUE TITLE
Polyfill a single image, and also windows compile problems

### ISSUE THREAD

**Issue by agamemnus** [chase-moskal/webp-hero#6]
A few issues --

1) First, compiling on Windows is a bit of a nightmare. There's no "cat" and no "rimraf". Have to use concat-cli, although rimraf is available as a CLI. It might be better to make a file to combine/remove files instead of using the CLI.

2) The uglify CLI uses an old method, although it still works, I guess.

3) Need to install the concat-cli CLI for the build to work.

4) Vulnerabilities? Auto-fixed.

5) Reason for re-compiling: I wanted to add a function that would modify a single image, since Javascript code tends to load images on the fly.

My scripts property in package.json:
````
	"scripts": {
		"start": "http-server",
		"prepare": "run-s clean wrap minify compile bundle",
		"clean": "rimraf dist && mkdir dist",
		"wrap": "concat-cli -f source/wrapping.js.start.txt libwebpjs/dist/webp.js source/wrapping.js.end.txt -o dist/dwebp.raw.js",
		"minify": "uglifyjs -cm < dist/dwebp.raw.js -o dist/dwebp.js && rimraf dist/dwebp.raw.js",
		"compile": "tsc",
		"bundle": "browserify -p [ tsify ] source/webp-hero.polyfill.ts > dist/webp-hero.polyfill.bundle.js",
		"test": "exit 0"
	},
````

And then devDependencies:
````
	"devDependencies": {
		"browserify": "16.2.3",
		"http-server": "0.11.1",
		"npm-run-all": "4.1.3",
		"tsify": "4.0.0",
		"typescript": "3.0.1",
		"uglify-js": "3.4.7",
		"concat-cli": "4.0.0",
		"rimraf": "2.6.3"
	}
````

My function (edited):
````
    async polyfillGroup({imageList, force = false}: {imageList?: Array<HTMLImageElement>, force?: boolean} = {}): Promise<void> {
		if (!force && await detectWebpSupport()) return undefined
		let hero = this
		for (const image of imageList) {
			let src = undefined
			if (image['srcNext'] !== undefined) {src = image['srcNext']} else {src = image.src}
			if (!(/.webp$/.test(src))) continue
			if (this.cache[src]) {image.src = this.cache[src]; continue}
			try {
                		const webpdata = await loadBinaryData(src)
                		const tryNow = async function () {
					const pngdata = await hero.decode(webpdata)
					image.src = hero.cache[src] = pngdata
				}
				if (!hero.busy) {
					tryNow()
				} else {
					let testInterval = window.setInterval(function () {
						if (!hero.busy) {window.clearInterval(testInterval); tryNow()}
					}, 50)
				}
			} catch (error) {
				console.error(`error decoding webp image "${src}"`, error)
				throw error
			}
		}
	}
````

**Comment by chase-moskal** [comment]
hello @agamemnus 

partly in response to this issue, i have updated and refactored webp-hero significantly :)

`webp-hero@0.0.0-dev.15`

1. **compiling on windows**
    - the webp-hero build is now more cross-platform and should build on windows (no longer uses `cat`, and uses locally-installed `rimraf` and `mkdirp`)
    - the concatenation logic (to build the webp.js commonjs module) has been moved inside the libwebp docker container build
2. **uglify cli old method**
    - uglify is no longer being used (it stopped working for some reason, it was stalling)
3. **replace cat usage with cross-platform concat-cli**
    - done, cat is now used inside the linux docker container
4. **npm security vulnerabilities**
    - all packages updated, all vulnerabilities fixed
5. **want to add function to modify single image**
    - class `WebpHero` has been replaced by `WebpMachine`
    - class `WebpMachine` has method `polyfillImage` which you can use to polyfill a single `<img>` element for more direct control
    - functions like `loadBinaryData` and `detectWebpSupport` are now made available

some more info about major changes since `v0.0.0-dev.12` in the [changelog](https://github.com/chase-moskal/webp-hero/blob/master/CHANGELOG.md)

**Comment by agamemnus** [comment]
I will check it out. Thank you.
